"""
Insights API routes for LLM-generated analytics insights.
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional

from services.analytics_service import get_analytics_service
from services.llm_service import get_llm_service

router = APIRouter()


class InsightRequest(BaseModel):
    """Request model for generating insights"""
    article_id: str
    sales_data: Optional[dict] = None
    context: Optional[str] = None


class Insight(BaseModel):
    """Single insight generated by LLM"""
    type: str  # e.g., "trend", "anomaly", "recommendation"
    title: str
    description: str
    confidence: float


class InsightsResponse(BaseModel):
    """Response with AI-generated insights"""
    article_id: str
    summary: str
    insights: List[Insight]


@router.post("/insights", response_model=InsightsResponse)
async def generate_insights(request: InsightRequest):
    """
    Generate AI-powered insights about a product's sales performance.
    Uses LLM (OpenAI GPT-4) to analyze sales data and provide human-readable insights.
    This is a REAL implementation with actual LLM integration.
    
    Args:
        request: InsightRequest with product ID and optional context
        
    Returns:
        InsightsResponse with generated insights
    """
    # Get sales summary and product info
    analytics = get_analytics_service()
    sales_summary = analytics.get_sales_summary(request.article_id)
    product = analytics.get_product_by_id(request.article_id)
    
    if not product:
        raise HTTPException(status_code=404, detail="Product not found")
    
    # Generate insights using LLM
    llm = get_llm_service()
    insights = llm.generate_insights(request.article_id, sales_summary, product)
    
    return insights

